### ISSUE TITLE
If 'openwrt' dir exists, why to remove it and do a fresh clean?

### ISSUE THREAD

**Issue by L337hium** [bittorf/kalua#11]
Lets asume I have in my kalua repo a directory 'build-env/'...

```
mkdir build-env
cd build-env

mkdir download_openwrt
../openwrt-build/build.sh --openwrt trunk 

cd openwrt
../../openwrt-build/build.sh --openwrt trunk --hardware 'TP-LINK TL-WDR3600' --usecase 'OpenWrt'

cd ..
# and a second time
../openwrt-build/build.sh --openwrt trunk 
# then 'openwrt/' will be removed, and I have to start from scratch.
```

Is that a bug or a feature (that 'openwrt/' will be removed, and cloned from scratch)?

**Comment by bittorf** [comment]
checking it...

**Comment by bittorf** [comment]
this is a feature, but i have added more warnings / explicit question before autoremoving with 98dcbe3f15383b73b518d3d1d6e999a5143889c8

the idea is this:
$yourdir/test1/openwrt
$yourdir/test2/openwrt
 
or simply use only 1 openwrt-dir and build everyhthing there
