### ISSUE TITLE
Links auf hopglass.weimarnetz.de

### ISSUE THREAD

**Issue by mtippmann** [bittorf/kalua#15]
Hallo, wir haben noch eine [neue Karte](https://hopglass.weimarnetz.de) und dort werden die Links anders dargestellt - dort wird im JSON die `id` genutzt und das ist wohl für den Link immer das Ziel. 

Im Code hier: https://github.com/bittorf/kalua/blob/master/openwrt-addons/etc/kalua/olsr#L1812

```
	"olsr_ipv4": {
		"localIP": "$LOCAL",
		"linkQuality": $LQ,
		"validityTime": 3600,
		"remoteIP": "$REMOTE",
		"neighborLinkQuality": $NLQ,
		"linkCost": ${COST:-0}
	},
	"sourceAddr4": "$LOCAL",
	"destAddr4": "$REMOTE",
	"ifname": "$dev",
	"id": "$HOSTNAME.olsr",
	"mac": "$devmac",
	"interface": "$devname",
	"quality": ${COST:-0}
	},
```

müsste bei id anstatt der Hostname des Hosts der Hostnames des Zieles sein - die Info müsste auch über das olsr jsoninfo plugin verfügbar sein. Der Code in owm.lua holt sich die Infos zumindest über das jsoninfo-Plugin - dann würden links auch korrekt angezeigt - momentan zeigen die Links deswegen nur auf sich selbst - siehe z.B. hier: https://hopglass.weimarnetz.de/#!v:m;n:exMeyer23.olsr

Ein 2. kleineres Problem ist das Feld `quality` - dort müsste nur `$LQ` rein und nicht `$COST`. 

Dann sind auch alle Knoten korrekt in der Karte. 

Ich hab es nicht hinbekommen das nur über die IPs zu lösen - am einfachsten wäre es wenn die 2 kleinen Änderungen noch eingebaut würden. 

Liebe Grüße

**Comment by glycoknob** [comment]
Müsste viel einfacher gehen - man braucht nur einen DNS-Lookup für die Ziel-IP - die Daten dafür müssten ja durch OLSR in dnsmasq sein. Ich versuch mal nen Pull-Request zu basteln.

**Comment by bittorf** [comment]
wegen quality, danke - habs gefixt: https://github.com/bittorf/kalua/commit/c6421e0379a319b8466d1677d6b67dde20a513dd

**Comment by bittorf** [comment]
ich werde diese woche noch ein update alles router starten.
