### ISSUE TITLE
Don't log user credentials to system logs

### ISSUE THREAD

**Issue by arky** [bittorf/kalua#4]
It is good idea not to log user credentials to system logs. 

Snip from system logs: 
 
Sat Apr 19 10:20:43 2014 daemon.alert fff+ /www/cgi-bin-welcome.sh weblogin_login_check(): wrong credentials: mac: 98:0c:82:90:e3:75 user: 'XXX' pass: 'XXX' hash: 'XXXXHASHXXX' DB: no_db_found

**Comment by bittorf** [comment]
this is only done with _wrong_ credentials for debugging.
