### ISSUE TITLE
Captive Portal Fails to redirect HTTPS 

### ISSUE THREAD

**Issue by arky** [bittorf/kalua#7]
Captive portal fails to redirect HTTPS requests to login page. Technically requests 'https://google.com' should be redirected to login page, however the browser (Firefox Nightly) throws a HTTPS error.

**Comment by bittorf** [comment]
all major browsers complain about a "man-in-the-middle-attack" which is technically correct.

solution can be:
reject/drop https till the user has unsplashed via http

**Comment by bittorf** [comment]
with 6c3e41ed4e19821bd98c619f4c958e9ba5407af1 the redirect for https is disabled.
